{{- if .Values.notificationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-notification
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
spec:
  type: {{ .Values.notificationService.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.notificationService.service.port | default 8001 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "taskflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
{{- end }}
