{{- if and .Values.sso.enabled .Values.sso.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.sso.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskflow.componentLabels" (dict "root" . "component" "sso") | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.sso.ingress.className }}
  rules:
  - host: {{ .Values.sso.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.sso.name }}
            port:
              number: {{ .Values.sso.service.port }}
  {{- if .Values.sso.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.sso.ingress.host }}
    secretName: {{ .Values.sso.name }}-tls
  {{- end }}
{{- end }}
